language: cpp
compiler: clang
os: linux

addons:
  apt:
    packages:
      - clang-3.5

install:
  - clang --version
  - export CC=clang-3.5
  - export CXX=clang++-3.5
  - $CC --version
  - $CXX --version

script: make all test
